force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Lwc_fullCalendarTest.cls
@isTest
public class Lwc_fullCalendarTest {

    @isTest
    static void testGetVisits() {

        Contact c = new Contact(LastName ='aaa');
        insert c;

        // Create test data
        Visit__c visit = new Visit__c(
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addDays(1),
            Contact__c = c.Id 
        );
        insert visit;

        // Call the method being tested
        List<Visit__c> result = Lwc_fullCalendar.getVisits();
       
    }
}