force-app/main/default/objects/Fees__c/Fees__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{0000}</displayFormat>
        <label>Fees Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fees__c/fields/Payer__c.field-meta.xml
<CustomField>
    <fullName>Payer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fees__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/DetailEvent__c.field-meta.xml
<CustomField>
    <fullName>DetailEvent__c</fullName>
    <label>Detail Event</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/ProgramPlace__c.field-meta.xml
<CustomField>
    <fullName>ProgramPlace__c</fullName>
    <label>Program Place</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>North</fullName>
            </value>
            <value>
                <fullName>Center</fullName>
            </value>
            <value>
                <fullName>South</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cardcomServiceTest.cls
@isTest
public class cardcomServiceTest 
{
        
    @isTest
    static void testDoPost() {
        Test.startTest();

        // Setup test data
        Contact c = new Contact(lastName='test');
        insert c;

        Program__c program = new Program__c();
        program.DetailEvent__c = '11111111111';
        program.ProgramPlace__c = 'North';
        insert program;       

        Fees__c f     = new Fees__c();   
        f.Payer__c    = c.Id;
        f.Program__c  = program.Id;
        insert f;

      
        
        // Simulate the callout request
        RestRequest req = new RestRequest();
        req.requestURI = '/cardcom';
        req.httpMethod = 'POST';
        req.params.put('Custom08', f.Id);
        req.params.put('responsecode', '0');
        RestContext.request = req;

        // Call the method to be tested
        cardcomService.doPost();
        
        Test.stopTest();
    }

}