force-app/main/default/objects/Cardcom_Logger__c/Cardcom_Logger__c.object-meta.xml
<CustomObject>
    <label>Cardcom Logger</label>
    <nameField>
        <displayFormat>ccl-{0000}</displayFormat>
        <label>Cardcom Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cardcom Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cardcom_Logger__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cardcom_Logger__c/fields/Card__c.field-meta.xml
<CustomField>
    <fullName>Card__c</fullName>
    <label>Card owner Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cardcom_Logger__c/fields/Card_owner_name__c.field-meta.xml
<CustomField>
    <fullName>Card_owner_name__c</fullName>
    <label>Card owner name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cardcom_Logger__c/fields/Internal_Deal_number__c.field-meta.xml
<CustomField>
    <fullName>Internal_Deal_number__c</fullName>
    <label>Internal Deal number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cardcom_Logger__c/fields/Response_Description__c.field-meta.xml
<CustomField>
    <fullName>Response_Description__c</fullName>
    <label>Response Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Fees__c/Fees__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>Fee-{0000}</displayFormat>
        <label>Fees Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fees__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fees__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fees__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting for payment</fullName>
                <default>true</default>
                <label>Waiting for payment</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cardcomService.cls
@restresource(urlMapping='/cardcom/*')
global class cardcomService 
{
   @httpPost
   global static void doPost()
   {
     
    //Recieve a callout request   
     RestRequest restReq = RestContext.request; 
    //  restReq.addHeader('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8');
     system.debug('Request:'+restReq);
     string paymentInfo;
     
     try
     {
        //Contains the request body- the payment information
        Map<String, String> requestParams = restReq.params;  
        system.debug('Payment information from cardcom:');
        system.debug(requestParams);
        
        //get the fee Id which the payment submmited to
        string feeId = requestParams.get('Custom08');
        system.debug('fee Id : '+ feeId);       

        if(feeId != null)
        {
            //get the response code when 0= payment succeded
            string responsecode =  requestParams.get('responsecode');
            system.debug('Response Code:'+responsecode);            
        
            //get the Last payment record for this particpation
            List<Fees__c> fees = new List<Fees__c>();
            fees = [Select Id, Payment_Status__c  FROM Fees__c WHERE Id =:feeId ORDER BY LastModifiedDate DESC] ;
            if(fees.size() > 0)
            {    
                Fees__c feeToUpdate = fees[0];                                         
                //Update payment record     
                feeToUpdate.Payment_Status__c                 = responsecode =='0'?'Paid':'Error';
                if(responsecode != '0')
                    feeToUpdate.Error_Description__c          = EncodingUtil.urlDecode(EncodingUtil.urlEncode(requestParams.get('responsdescription'), 'ISO_8859_1'), 'UTF8');    
                if(requestParams.get('suminfull')!=null)
                    feeToUpdate.Amount_Paid__c                = Decimal.valueOf(requestParams.get('suminfull'));

                update feeToUpdate;

                // if(requestParams.get('suminfull')!=null)
                //     paymentToUpdate.Actual_Amount__c        = Decimal.valueOf(requestParams.get('suminfull'));
                // paymentToUpdate.Actual_Date__c          = System.today();    
                //paymentToUpdate.Response_Description__c = requestParams.get('responsdescription');             
                //paymentToUpdate.Response_Description__c = EncodingUtil.urlDecode(EncodingUtil.urlEncode(requestParams.get('responsdescription'), 'ISO_8859_1'), 'UTF8');                // paymentToUpdate.Response_Description__c = '';
                // for (String key: requestParams.keyset()){        
                //     paymentToUpdate.Response_Description__c += key+':'+requestParams.get(key);                
                //     }
                // paymentToUpdate.Card_Owner_Name__c      = requestParams.get('CardOwnerName');
                // paymentToUpdate.Card_Owner_ID__c        = requestParams.get('CardOwnerID');
                // String curr = '';
                // if (requestParams.get('cointype') == '1' || requestParams.get('cointype') == '8')
                //     curr = 'ILS';
                // if (requestParams.get('cointype') == '2' || requestParams.get('cointype') == '4')
                //     curr = 'USD';
                // paymentToUpdate.Currency__c             = curr;
                // paymentToUpdate.Deal_Number__c          = requestParams.get('internaldealnumber');
                // paymentToUpdate.Approvel_Number__c      = requestParams.get('ApprovelNumber');
                // if(requestParams.get('NumberOfPaymentsToPrint')!=null)
                //     paymentToUpdate.Number_Of_Payments__c   = Decimal.valueOf(requestParams.get('NumberOfPaymentsToPrint'));               
    
            }
            else 
            {
                system.debug('cardcom service error:'+ 'No Payments found for fee ' + feeId);
            }                       
        }
        else 
        {
            system.debug('cardcom service error:'+ 'No fee ID');
        }  
        Cardcom_Logger__c ccl = new Cardcom_Logger__c();
        //ccl.Response_Description__c = requestParams.get('responsdescription');  
        ccl.Response_Description__c = EncodingUtil.urlDecode(EncodingUtil.urlEncode(requestParams.get('responsdescription'), 'ISO_8859_1'), 'UTF8');               
        ccl.Fee_Id__c               = feeId;
        ccl.Card_owner_name__c      = EncodingUtil.urlDecode(EncodingUtil.urlEncode(requestParams.get('CardOwnerName'), 'ISO_8859_1'), 'UTF8');
        ccl.Card__c                 = requestParams.get('CardOwnerID');
        if(requestParams.get('suminfull')!=null)
            ccl.Amount_Paid__c          = Decimal.valueOf(requestParams.get('suminfull'));
        ccl.Internal_Deal_number__c     = requestParams.get('internaldealnumber');
        insert ccl;     
     }
     catch (Exception ex) 
     {
        system.debug('cardcom service error:'+ex.getMessage());
     }

   }
}